# Pandas Basics

## The standard Numpy and Pandas imports

In [1]:
import numpy as np
import pandas as pd

## Load the CSV

In [2]:
df = pd.read_csv('origins-game-fair-2025-schedule.csv')

## Examine the Dataframe

In [20]:
df.columns

Index(['Event Name', 'Event Number', 'Event Type', 'Host Names', 'Description',
       'Price', 'Age Range', 'Max Tickets', 'Sold Count', 'Wait Count',
       'Starts', 'Start Date (UTC)', 'Duration (minutes)', 'More Info', 'Room',
       'Space', 'Date Created', 'Date Updated', 'View URI', 'All Events',
       'Collectible Games Badge', 'Media Events', 'Mermbers Only',
       'Tounament of Pieces', 'Game Master (GM)', 'Game Edition',
       'Game Publisher', 'Game Complexity', 'Player Experience',
       'Rules Taught', 'Is your event a tournament?',
       'What style of tournament', 'Tournament Stage/Round', 'Sub-Category',
       'Hosting Company, Group, or Club', 'Game System',
       'Will characters be provided?'],
      dtype='object')

In [5]:
df.dtypes

Event Name                         object
Event Number                        int64
Event Type                         object
Host Names                         object
Description                        object
Price                               int64
Age Range                          object
Max Tickets                         int64
Sold Count                          int64
Wait Count                          int64
Starts                             object
Start Date (UTC)                   object
Duration (minutes)                  int64
More Info                          object
Room                               object
Space                              object
Date Created                       object
Date Updated                       object
View URI                           object
All Events                          int64
Collectible Games Badge             int64
Media Events                        int64
Mermbers Only                       int64
Tounament of Pieces                 int64
Game Master (GM)                   object
Game Edition                       object
Game Publisher                     object
Game Complexity                    object
Player Experience                  object
Rules Taught                       object
Is your event a tournament?        object
What style of tournament           object
Tournament Stage/Round             object
Sub-Category                       object
Hosting Company, Group, or Club    object
Game System                        object
Will characters be provided?       object
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7815 entries, 0 to 7814
Data columns (total 37 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Event Name                       7815 non-null   object
 1   Event Number                     7815 non-null   int64
 2   Event Type                       7815 non-null   object
 3   Host Names                       7815 non-null   object
 4   Description                      7814 non-null   object
 5   Price                            7815 non-null   int64
 6   Age Range                        7815 non-null   object
 7   Max Tickets                      7815 non-null   int64
 8   Sold Count                       7815 non-null   int64
 9   Wait Count                       7815 non-null   int64
 10  Starts                           7815 non-null   object
 11  Start Date (UTC)                 7815 non-null   object
 12  Duration (minutes)               7815 non-null   int64
 13  More Info                        4290 non-null   object
 14  Room                             7815 non-null   object
 15  Space                            7815 non-null   object
 16  Date Created                     7815 non-null   object
 17  Date Updated                     7815 non-null   object
 18  View URI                         7815 non-null   object
 19  All Events                       7815 non-null   int64
 20  Collectible Games Badge          7815 non-null   int64
 21  Media Events                     7815 non-null   int64
 22  Mermbers Only                    7815 non-null   int64
 23  Tounament of Pieces              7815 non-null   int64
 24  Game Master (GM)                 7716 non-null   object
 25  Game Edition                     5888 non-null   object
 26  Game Publisher                   7116 non-null   object
 27  Game Complexity                  7291 non-null   object
 28  Player Experience                7291 non-null   object
 29  Rules Taught                     7291 non-null   object
 30  Is your event a tournament?      7291 non-null   object
 31  What style of tournament         368 non-null    object
 32  Tournament Stage/Round           368 non-null    object
 33  Sub-Category                     5540 non-null   object
 34  Hosting Company, Group, or Club  7301 non-null   object
 35  Game System                      2534 non-null   object
 36  Will characters be provided?     1815 non-null   object
dtypes: int64(11), object(26)
memory usage: 2.2+ MB

In [6]:
len(df)  # how many rows

7815

In [7]:
df.index

RangeIndex(start=0, stop=7815, step=1)

## Inspect values within field

In [27]:
df['Event Type'].value_counts()

Event Type
Board Game                      3026
Roleplaying Game                1765
Miniatures Game                  777
Live Action Roleplaying Game     770
Card Game                        499
Social Deduction/Deception       305
Workshop                         275
Seminars and Panels              156
Media Only                        99
Eclectic                          68
Puzzle Games                      32
Entertainment                     25
Classic Games                     18
Name: count, dtype: int64

## Narrow down to columns of interest

In [23]:
columns_of_interest = [
    'Event Name', 'Event Number', 'Event Type',
    'Description', 'Price', 'Age Range',
    'Max Tickets', 'Sold Count', 'Wait Count',
    'Start Date (UTC)', 'Duration (minutes)', 'Room',
    'Space', 'Mermbers Only', 'Rules Taught',
    'Will characters be provided?',
]

In [24]:
df[columns_of_interest]

,Event Name,Event Number,Event Type,Description,Price,Age Range,Max Tickets,Sold Count,Wait Count,Start Date (UTC),Duration (minutes),Room,Space,Mermbers Only,Rules Taught,Will characters be provided?
0,Trade Day,9174,Seminars and Panels,Origins Trade Day 2025 is a daylong educationa...,0,Adult (18+),250,152,0,2025-06-18T12:00:00,570,GCCC - 2nd Floor - Meeting Room A 216 - Seminars,Room,1,NaN,NaN
1,End of the Line - 2nd Edition,5855,Board Game,"Line up hoping to collect: food, water, fuel &...",0,Teen Friendly (13+),5,5,2,2025-06-18T16:00:00,120,GCCC - Hall C - 2430 - 6x30 Tables,Table 05,0,Yes,NaN
2,Wayward Spacers - 25 Minute Escape Room,7910,Live Action Roleplaying Game,Adrift in space and supplies are running low –...,22,Teen Friendly (13+),4,0,0,2025-06-18T16:00:00,30,GCCC - 1st Floor - Meeting Room B 132 - Unphazed,Table 01,0,Yes,NaN
3,"Capital City Crimewave, Episode 325",5727,Roleplaying Game,Villains are on the loose in Capital City! The...,0,Teen Friendly (13+),6,6,0,2025-06-18T16:00:00,120,GCCC - 1st Floor - Meeting Room D 180/181 - Pr...,Table 02,0,Yes,Yes
4,Gunfights & Gamblin' Second Edition,3930,Board Game,A gut-punch of a game that pits two to six pla...,0,Teen Friendly (13+),6,6,0,2025-06-18T16:00:00,120,GCCC - Hall C - 2108 - Mid Level Meeple,Table 03 - 6'x30' Rectangle,0,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7810,Big Dig - 25 Minute Escape Room,7487,Live Action Roleplaying Game,Careful investigation of these ruins will reve...,22,Teen Friendly (13+),4,0,0,2025-06-22T19:30:00,30,GCCC - 1st Floor - Meeting Room B 132 - Unphazed,Table 01,0,Yes,NaN
7811,Build A Foam Sword,5491,Workshop,We are back for yet another amazing year! Come...,14,All Ages (12 and under must be with an adult),20,0,0,2025-06-22T19:30:00,30,GCCC - 2nd Floor - Meeting Room A 220 - Strong...,Table 2,0,NaN,NaN
7812,Sword In The Wall - 25 Minute Escape Room,7810,Live Action Roleplaying Game,Only the worthy may pull the sword out! Maybe ...,22,Teen Friendly (13+),4,0,0,2025-06-22T19:30:00,30,GCCC - 1st Floor - Meeting Room B 132 - Unphazed,Table 04,0,Yes,NaN
7813,Elixir Mixir - 25 Minute Escape Room,7595,Live Action Roleplaying Game,By following the cryptic instructions of a mis...,22,Teen Friendly (13+),4,0,0,2025-06-22T19:30:00,30,GCCC - 1st Floor - Meeting Room B 132 - Unphazed,Table 02,0,Yes,NaN
7814,Wayward Spacers - 25 Minute Escape Room,7856,Live Action Roleplaying Game,Adrift in space and supplies are running low –...,22,Teen Friendly (13+),4,0,0,2025-06-22T19:30:00,30,GCCC - 1st Floor - Meeting Room B 132 - Unphazed,Table 05,0,Yes,NaN

## Get status for some numeric fields

In [46]:
df[['Price', 'Max Tickets', 'Duration (minutes)']].describe()

            Price  Max Tickets  Duration (minutes)
count  7815.00000  7815.000000         7815.000000
mean      4.84453    10.845425          131.619962
std      10.97069    22.534617           85.677184
min       0.00000     0.000000           30.000000
25%       0.00000     4.000000           60.000000
50%       0.00000     6.000000          120.000000
75%       4.00000    10.000000          180.000000
max     242.00000   360.000000          600.000000

## Convert field with string representation of a UTC date into local datetime

In [48]:
# The original string field
df['Start Date (UTC)']

0       2025-06-18T12:00:00
1       2025-06-18T16:00:00
2       2025-06-18T16:00:00
3       2025-06-18T16:00:00
4       2025-06-18T16:00:00
               ...
7810    2025-06-22T19:30:00
7811    2025-06-22T19:30:00
7812    2025-06-22T19:30:00
7813    2025-06-22T19:30:00
7814    2025-06-22T19:30:00
Name: Start Date (UTC), Length: 7815, dtype: object

In [49]:
# Convert string to datetime
df['start_date'] = pd.to_datetime(df['Start Date (UTC)'])

In [50]:
# Check the type of the resulting column
df['start_date'].dtypes

dtype('<M8[ns]')

In [51]:
# <M8[ns] is the datetime datatype used by Pandas.  Convert to local time

# This causes a "Cannot convert tz-naive timestamps, use tz_localize to localize"
# apparently my start_date_utc, doesn't have a timezone
#df['start_date_nyc'] = df['start_date_utc'].dt.tz_convert('America/New_York')

# create column with UTC timezone
df['start_date_utc'] = df['start_date'].dt.tz_localize('UTC')

# Now we can create a column with the local time
df['start_date_local'] = df['start_date_utc'].dt.tz_convert('America/New_York')

In [43]:
start_date_fields = ['Start Date (UTC)', 'start_date', 'start_date_utc', 'start_date_local']

# Inspect types of the fields
df[start_date_fields].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7815 entries, 0 to 7814
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Start Date (UTC)  7815 non-null   object
 1   start_date        7815 non-null   datetime64[ns]
 2   start_date_utc    7815 non-null   datetime64[ns, UTC]
 3   start_date_local  7815 non-null   datetime64[ns, America/New_York]
dtypes: datetime64[ns, America/New_York](1), datetime64[ns, UTC](1), datetime64[ns](1), object(1)
memory usage: 244.3+ KB

In [45]:
# See what the data looks like
df[start_date_fields].head(5)

,Start Date (UTC),start_date,start_date_utc,start_date_local
0,2025-06-18T12:00:00,2025-06-18 12:00:00,2025-06-18 12:00:00+00:00,2025-06-18 08:00:00-04:00
1,2025-06-18T16:00:00,2025-06-18 16:00:00,2025-06-18 16:00:00+00:00,2025-06-18 12:00:00-04:00
2,2025-06-18T16:00:00,2025-06-18 16:00:00,2025-06-18 16:00:00+00:00,2025-06-18 12:00:00-04:00
3,2025-06-18T16:00:00,2025-06-18 16:00:00,2025-06-18 16:00:00+00:00,2025-06-18 12:00:00-04:00
4,2025-06-18T16:00:00,2025-06-18 16:00:00,2025-06-18 16:00:00+00:00,2025-06-18 12:00:00-04:00

In [52]:
from datetime import datetime
from zoneinfo import ZoneInfo

nyc_timezone = ZoneInfo('America/New_York')

# Events on Sunday the 22nd
df[df['start_date_nyc'] > datetime(2025, 6, 22, tzinfo=nyc_timezone)]

,Event Name,Event Number,Event Type,Host Names,Description,Price,Age Range,Max Tickets,Sold Count,Wait Count,...,What style of tournament,Tournament Stage/Round,Sub-Category,"Hosting Company, Group, or Club",Game System,Will characters be provided?,start_date_utc,start_date,start_date_nyc,start_date_local
7168,Empire Builder: Europe Finals,3299,Board Game,Trella Bromley,Win one Eurorails Qualifying event to advance ...,0,Teen Friendly (13+),24,0,0,...,Swiss,Final,Train Game,Train Gamers Association,NaN,NaN,2025-06-22 12:00:00+00:00,2025-06-22 12:00:00,2025-06-22 08:00:00-04:00,2025-06-22 08:00:00-04:00
7169,Press and Media Recording Room- B244,9885,Media Only,Lindsay France,Please schedule for up to two hour blocks of t...,0,All Ages (12 and under must be with an adult),1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,2025-06-22 12:00:00+00:00,2025-06-22 12:00:00,2025-06-22 08:00:00-04:00,2025-06-22 08:00:00-04:00
7170,80’s D&D Cartoon Adventures with Level 4 Heroe...,6346,Roleplaying Game,Whoctor,The displaced kids (now young adults) from the...,0,Teen Friendly (13+),6,6,6,...,NaN,NaN,Fantasy,NaN,Dungeons and Dragons,Yes,2025-06-22 12:00:00+00:00,2025-06-22 12:00:00,2025-06-22 08:00:00-04:00,2025-06-22 08:00:00-04:00
7171,Amtgard 101,1789,Live Action Roleplaying Game,Elliott Hedrick,Come learn the basics of foam combat! This wil...,0,Teen Friendly (13+),16,2,0,...,NaN,NaN,Fantasy,The Rising Winds,Amtgard,NaN,2025-06-22 12:00:00+00:00,2025-06-22 12:00:00,2025-06-22 08:00:00-04:00,2025-06-22 08:00:00-04:00
7172,Potion Explosion,264,Board Game,Iejir,"Dear students, It's time for the final exams o...",0,"Kid Friendly (8+, 12 and under must be with an...",8,8,0,...,NaN,NaN,Educational,Iejir Works,NaN,NaN,2025-06-22 12:00:00+00:00,2025-06-22 12:00:00,2025-06-22 08:00:00-04:00,2025-06-22 08:00:00-04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7810,Big Dig - 25 Minute Escape Room,7487,Live Action Roleplaying Game,Unphazedgames@gmail.com,Careful investigation of these ruins will reve...,22,Teen Friendly (13+),4,0,0,...,NaN,NaN,Cooperative,Co-Operatives,Escape Room,NaN,2025-06-22 19:30:00+00:00,2025-06-22 19:30:00,2025-06-22 15:30:00-04:00,2025-06-22 15:30:00-04:00
7811,Build A Foam Sword,5491,Workshop,Joell,We are back for yet another amazing year! Come...,14,All Ages (12 and under must be with an adult),20,0,0,...,NaN,NaN,NaN,StrongHold LARP Foam,NaN,NaN,2025-06-22 19:30:00+00:00,2025-06-22 19:30:00,2025-06-22 15:30:00-04:00,2025-06-22 15:30:00-04:00
7812,Sword In The Wall - 25 Minute Escape Room,7810,Live Action Roleplaying Game,Unphazedgames@gmail.com,Only the worthy may pull the sword out! Maybe ...,22,Teen Friendly (13+),4,0,0,...,NaN,NaN,Cooperative,Co-Operatives,Escape Room,NaN,2025-06-22 19:30:00+00:00,2025-06-22 19:30:00,2025-06-22 15:30:00-04:00,2025-06-22 15:30:00-04:00
7813,Elixir Mixir - 25 Minute Escape Room,7595,Live Action Roleplaying Game,Unphazedgames@gmail.com,By following the cryptic instructions of a mis...,22,Teen Friendly (13+),4,0,0,...,NaN,NaN,Cooperative,Co-Operatives,Escape Room,NaN,2025-06-22 19:30:00+00:00,2025-06-22 19:30:00,2025-06-22 15:30:00-04:00,2025-06-22 15:30:00-04:00
7814,Wayward Spacers - 25 Minute Escape Room,7856,Live Action Roleplaying Game,Unphazedgames@gmail.com,Adrift in space and supplies are running low –...,22,Teen Friendly (13+),4,0,0,...,NaN,NaN,Cooperative,Co-Operatives,Escape Room,NaN,2025-06-22 19:30:00+00:00,2025-06-22 19:30:00,2025-06-22 15:30:00-04:00,2025-06-22 15:30:00-04:00

## Resources

* https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html